export const CUSTOM_PRESET_ID_PREFIX = "custom:";
export const GENERATED_PRESET_AGENT_COUNT_DEFAULT = 3;
export const GENERATED_PRESET_AGENT_COUNT_MIN = 2;
export const GENERATED_PRESET_AGENT_COUNT_MAX = 8;
